global:
  prefix: "&aBlock By Block"
  server-type: "CORE" #LOBBY, CORE
  proxy-server-name: ""
  debug: true
actions:
  break-blocks: false
  place-blocks: false
  player-interact-at-entity: false
  player-interact-entity: false
  player-bed-events: false
  player-drop-items: false
  player-pickup-items: false
  consume-items: false
spawn:
  location:
db:
  #MongoDB
  host: 207.244.238.225
  port: 27017
  user: bbb
  password: djj200akdlll2kKASDJJ2KA
  database: bbb
  urli: "mongodb://bbb:djj200akdlll2kKASDJJ2KA@207.244.238.225:27017/?directConnection=true"


perms:
  when-creating-world:
    - fawe.bypass
    - arceon.*
    - voxelsniper.*
    - worldedit.*
    - gopaint.use
    - gobrush.use
    - astools.use
    - models.use
    - builders.util.*
    - headdb.*
    - astools.use
  when-joining-world:
    - fawe.bypass
    - arceon.*
    - voxelsniper.*
    - worldedit.*
    - gopaint.use
    - gobrush.use
    - astools.use
    - models.use
    - builders.util.*
  when-joining-as-visitor-to-world:
