name: BlockByBlock
version: '${project.version}'
main: net.lymarket.comissionss.youmind.bbb.Main
depend:
  - SlimeWorldManager
  - LuckPerms
softdepend:
  - PlotSquared
  - PlaceholderAPI
load: POSTWORLD
api-version: 1.13
